FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir mlflow
EXPOSE 5000
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mlruns/mlflow.db", "--default-artifact-root", "file:///mlruns/artifacts"]
