{
 "title": "Drift-Aware MLOps Dashboard",
 "tags": [ "mlops" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Model Version",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "current_model_version" }
   ]
  },
  {
   "title": "Drift Severity",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "drift_severity" }
   ]
  },
  {
   "title": "Retrain Events",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "retrain_events_total" }
   ]
  },
  {
   "title": "Prediction Requests Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Prediction Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 12 },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[1m]) / rate(prediction_latency_seconds_count[1m])"
    }
   ]
  }
 ]
}